package com.hallth.mapper;

import com.hallth.domain.MytyScore;

import java.util.List;

public interface MytyScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_score
     *
     * @mbggenerated
     */
    int insert(MytyScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_score
     *
     * @mbggenerated
     */
    int insertSelective(MytyScore record);

    int insertList(List<MytyScore> list);

    List<MytyScore> getScoreByRoundNo(MytyScore scoreQueryBean);

    int getScoreByRoundNoCount(MytyScore scoreQueryBean);
}