package com.hallth.mapper;

import com.hallth.domain.MytyUser;

import java.util.List;

public interface MytyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_user
     *
     * @mbggenerated
     */
    int insert(MytyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_user
     *
     * @mbggenerated
     */
    int insertSelective(MytyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_user
     *
     * @mbggenerated
     */
    MytyUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MytyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MytyUser record);

    MytyUser loginCheck(MytyUser user);

    MytyUser getUserInfo(MytyUser user);

    int changePassword(MytyUser user);

    List<MytyUser> getAllUserInfo(MytyUser user);

    int getAllUserInfoCount(MytyUser user);

    int resetPassword(MytyUser user);

    int asDeveloper(MytyUser user);
}