package com.hallth.mapper;

import com.hallth.domain.MytyParam;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;

public interface MytyParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_param
     *
     * @mbggenerated
     */
    int insert(MytyParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_param
     *
     * @mbggenerated
     */
    int insertSelective(MytyParam record);

    List<MytyParam> getAllParam(MytyParam param);

    int updateParam(MytyParam record);

    int deleteParam(MytyParam record);

    int getAllParamCount(MytyParam param);

    String getValue(@RequestParam("paramId") String jiamishu);
}