package com.hallth.mapper;

import com.hallth.domain.MytySeq;

public interface MytySeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_seq
     *
     * @mbggenerated
     */
    int insert(MytySeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_seq
     *
     * @mbggenerated
     */
    int insertSelective(MytySeq record);

    int getNextId(MytySeq record);

    int update(MytySeq seq);
}