package com.hallth.mapper;

import com.hallth.domain.MytyLog;

import java.util.List;

public interface MytyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_log
     *
     * @mbggenerated
     */
    int insert(MytyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_log
     *
     * @mbggenerated
     */
    int insertSelective(MytyLog record);

    Integer selectByRoundNo(MytyLog log);
}