package com.hallth.mapper;

import com.hallth.domain.MytyDengmiTemp;

import java.util.List;

public interface MytyDengmiTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_dengmi_temp
     *
     * @mbggenerated
     */
    int insert(MytyDengmiTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_dengmi_temp
     *
     * @mbggenerated
     */
    int insertSelective(MytyDengmiTemp record);

    List<MytyDengmiTemp> selectByUserId(MytyDengmiTemp dengmiTemp);

    List<MytyDengmiTemp> selectNoAnswers(MytyDengmiTemp dengmiTemp);
}