package com.hallth.mapper;

import com.hallth.domain.MytyAgenda;

import java.util.List;

public interface MytyAgendaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_agenda
     *
     * @mbggenerated
     */
    int insert(MytyAgenda record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_agenda
     *
     * @mbggenerated
     */
    int insertSelective(MytyAgenda record);

    List<MytyAgenda> getNewAgendaDetail(MytyAgenda agenda);

    MytyAgenda getNewRoundNo();
}