package com.hallth.mapper;

import com.hallth.domain.MytyMenu;
import com.hallth.domain.MytyUser;

import java.util.List;

public interface MytyMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_menu
     *
     * @mbggenerated
     */
    int insert(MytyMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myty_menu
     *
     * @mbggenerated
     */
    int insertSelective(MytyMenu record);

    List<MytyMenu> getListByUserRole(MytyMenu menu);

    List<MytyUser> getAllMenuInfo(MytyMenu menu);

    int getAllMenuInfoCount(MytyMenu menu);

    int deleteMenu(MytyMenu menu);
}