package com.hallth.domain;

public class MytyDengmi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi.dm_id
     *
     * @mbggenerated
     */
    private Integer dmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi.dm_mimian
     *
     * @mbggenerated
     */
    private String dmMimian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi.dm_mimu
     *
     * @mbggenerated
     */
    private String dmMimu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi.dm_midi
     *
     * @mbggenerated
     */
    private String dmMidi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi.dm_mimianzhu
     *
     * @mbggenerated
     */
    private String dmMimianzhu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi.dm_midizhu
     *
     * @mbggenerated
     */
    private String dmMidizhu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi.dm_author
     *
     * @mbggenerated
     */
    private String dmAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi.dm_pingfen
     *
     * @mbggenerated
     */
    private Integer dmPingfen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi.dm_mingci
     *
     * @mbggenerated
     */
    private Integer dmMingci;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi.dm_wanzhonglv
     *
     * @mbggenerated
     */
    private Integer dmWanzhonglv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_dengmi.dm_id
     *
     * @return the value of myty_dengmi.dm_id
     *
     * @mbggenerated
     */
    public Integer getDmId() {
        return dmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_dengmi.dm_id
     *
     * @param dmId the value for myty_dengmi.dm_id
     *
     * @mbggenerated
     */
    public void setDmId(Integer dmId) {
        this.dmId = dmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_dengmi.dm_mimian
     *
     * @return the value of myty_dengmi.dm_mimian
     *
     * @mbggenerated
     */
    public String getDmMimian() {
        return dmMimian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_dengmi.dm_mimian
     *
     * @param dmMimian the value for myty_dengmi.dm_mimian
     *
     * @mbggenerated
     */
    public void setDmMimian(String dmMimian) {
        this.dmMimian = dmMimian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_dengmi.dm_mimu
     *
     * @return the value of myty_dengmi.dm_mimu
     *
     * @mbggenerated
     */
    public String getDmMimu() {
        return dmMimu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_dengmi.dm_mimu
     *
     * @param dmMimu the value for myty_dengmi.dm_mimu
     *
     * @mbggenerated
     */
    public void setDmMimu(String dmMimu) {
        this.dmMimu = dmMimu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_dengmi.dm_midi
     *
     * @return the value of myty_dengmi.dm_midi
     *
     * @mbggenerated
     */
    public String getDmMidi() {
        return dmMidi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_dengmi.dm_midi
     *
     * @param dmMidi the value for myty_dengmi.dm_midi
     *
     * @mbggenerated
     */
    public void setDmMidi(String dmMidi) {
        this.dmMidi = dmMidi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_dengmi.dm_mimianzhu
     *
     * @return the value of myty_dengmi.dm_mimianzhu
     *
     * @mbggenerated
     */
    public String getDmMimianzhu() {
        return dmMimianzhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_dengmi.dm_mimianzhu
     *
     * @param dmMimianzhu the value for myty_dengmi.dm_mimianzhu
     *
     * @mbggenerated
     */
    public void setDmMimianzhu(String dmMimianzhu) {
        this.dmMimianzhu = dmMimianzhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_dengmi.dm_midizhu
     *
     * @return the value of myty_dengmi.dm_midizhu
     *
     * @mbggenerated
     */
    public String getDmMidizhu() {
        return dmMidizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_dengmi.dm_midizhu
     *
     * @param dmMidizhu the value for myty_dengmi.dm_midizhu
     *
     * @mbggenerated
     */
    public void setDmMidizhu(String dmMidizhu) {
        this.dmMidizhu = dmMidizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_dengmi.dm_author
     *
     * @return the value of myty_dengmi.dm_author
     *
     * @mbggenerated
     */
    public String getDmAuthor() {
        return dmAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_dengmi.dm_author
     *
     * @param dmAuthor the value for myty_dengmi.dm_author
     *
     * @mbggenerated
     */
    public void setDmAuthor(String dmAuthor) {
        this.dmAuthor = dmAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_dengmi.dm_pingfen
     *
     * @return the value of myty_dengmi.dm_pingfen
     *
     * @mbggenerated
     */
    public Integer getDmPingfen() {
        return dmPingfen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_dengmi.dm_pingfen
     *
     * @param dmPingfen the value for myty_dengmi.dm_pingfen
     *
     * @mbggenerated
     */
    public void setDmPingfen(Integer dmPingfen) {
        this.dmPingfen = dmPingfen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_dengmi.dm_mingci
     *
     * @return the value of myty_dengmi.dm_mingci
     *
     * @mbggenerated
     */
    public Integer getDmMingci() {
        return dmMingci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_dengmi.dm_mingci
     *
     * @param dmMingci the value for myty_dengmi.dm_mingci
     *
     * @mbggenerated
     */
    public void setDmMingci(Integer dmMingci) {
        this.dmMingci = dmMingci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_dengmi.dm_wanzhonglv
     *
     * @return the value of myty_dengmi.dm_wanzhonglv
     *
     * @mbggenerated
     */
    public Integer getDmWanzhonglv() {
        return dmWanzhonglv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_dengmi.dm_wanzhonglv
     *
     * @param dmWanzhonglv the value for myty_dengmi.dm_wanzhonglv
     *
     * @mbggenerated
     */
    public void setDmWanzhonglv(Integer dmWanzhonglv) {
        this.dmWanzhonglv = dmWanzhonglv;
    }
}