package com.hallth.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class MytyAgenda {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_agenda.round_no
     *
     * @mbggenerated
     */
    private Integer roundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_agenda.start_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_agenda.do_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date doTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_agenda.judge_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date judgeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_agenda.end_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_agenda.input_count
     *
     * @mbggenerated
     */
    private Integer inputCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_agenda.round_no
     *
     * @return the value of myty_agenda.round_no
     *
     * @mbggenerated
     */
    public Integer getRoundNo() {
        return roundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_agenda.round_no
     *
     * @param roundNo the value for myty_agenda.round_no
     *
     * @mbggenerated
     */
    public void setRoundNo(Integer roundNo) {
        this.roundNo = roundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_agenda.start_time
     *
     * @return the value of myty_agenda.start_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_agenda.start_time
     *
     * @param startTime the value for myty_agenda.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_agenda.do_time
     *
     * @return the value of myty_agenda.do_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    public Date getDoTime() {
        return doTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_agenda.do_time
     *
     * @param doTime the value for myty_agenda.do_time
     *
     * @mbggenerated
     */
    public void setDoTime(Date doTime) {
        this.doTime = doTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_agenda.judge_time
     *
     * @return the value of myty_agenda.judge_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    public Date getJudgeTime() {
        return judgeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_agenda.judge_time
     *
     * @param judgeTime the value for myty_agenda.judge_time
     *
     * @mbggenerated
     */
    public void setJudgeTime(Date judgeTime) {
        this.judgeTime = judgeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_agenda.end_time
     *
     * @return the value of myty_agenda.end_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_agenda.end_time
     *
     * @param endTime the value for myty_agenda.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_agenda.input_count
     *
     * @return the value of myty_agenda.input_count
     *
     * @mbggenerated
     */
    public Integer getInputCount() {
        return inputCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_agenda.input_count
     *
     * @param inputCount the value for myty_agenda.input_count
     *
     * @mbggenerated
     */
    public void setInputCount(Integer inputCount) {
        this.inputCount = inputCount;
    }
}