package com.hallth.domain;

import java.util.Date;

public class MytyAgenda {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_agenda.round_no
     *
     * @mbggenerated
     */
    private Integer roundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_agenda.progress_point
     *
     * @mbggenerated
     */
    private String progressPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_agenda.progress_date
     *
     * @mbggenerated
     */
    private Date progressDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_agenda.round_no
     *
     * @return the value of myty_agenda.round_no
     *
     * @mbggenerated
     */
    public Integer getRoundNo() {
        return roundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_agenda.round_no
     *
     * @param roundNo the value for myty_agenda.round_no
     *
     * @mbggenerated
     */
    public void setRoundNo(Integer roundNo) {
        this.roundNo = roundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_agenda.progress_point
     *
     * @return the value of myty_agenda.progress_point
     *
     * @mbggenerated
     */
    public String getProgressPoint() {
        return progressPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_agenda.progress_point
     *
     * @param progressPoint the value for myty_agenda.progress_point
     *
     * @mbggenerated
     */
    public void setProgressPoint(String progressPoint) {
        this.progressPoint = progressPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_agenda.progress_date
     *
     * @return the value of myty_agenda.progress_date
     *
     * @mbggenerated
     */
    public Date getProgressDate() {
        return progressDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_agenda.progress_date
     *
     * @param progressDate the value for myty_agenda.progress_date
     *
     * @mbggenerated
     */
    public void setProgressDate(Date progressDate) {
        this.progressDate = progressDate;
    }
}