package com.hallth.domain;

public class MytyScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_score.agenda_round_no
     *
     * @mbggenerated
     */
    private Integer agendaRoundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_score.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_score.user_score
     *
     * @mbggenerated
     */
    private Integer userScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_score.score_type
     *
     * @mbggenerated
     */
    private String scoreType;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_score.score_type
     *
     * @mbggenerated
     */
    private Integer userAnsScore;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_score.score_type
     *
     * @mbggenerated
     */
    private Integer userSubScore;
    private float userAnsScorePer;
    private float userSubScorePer;

    public float getUserAnsScorePer() {
        return userAnsScorePer;
    }

    public void setUserAnsScorePer(float userAnsScorePer) {
        this.userAnsScorePer = userAnsScorePer;
    }

    public float getUserSubScorePer() {
        return userSubScorePer;
    }

    public void setUserSubScorePer(float userSubScorePer) {
        this.userSubScorePer = userSubScorePer;
    }

    private Integer sumScore;

    public Integer getSumScore() {
        return sumScore;
    }

    public void setSumScore(Integer sumScore) {
        this.sumScore = sumScore;
    }

    private int startRow;
    private int pageSize;

    private String user_name;

    public String getUser_name() {
        return user_name;
    }

    public Integer getUserAnsScore() {
        return userAnsScore;
    }

    public void setUserAnsScore(Integer userAnsScore) {
        this.userAnsScore = userAnsScore;
    }

    public Integer getUserSubScore() {
        return userSubScore;
    }

    public void setUserSubScore(Integer userSubScore) {
        this.userSubScore = userSubScore;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public int getStartRow() {
        return startRow;
    }

    public void setStartRow(int startRow) {
        this.startRow = startRow;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_score.agenda_round_no
     *
     * @return the value of myty_score.agenda_round_no
     *
     * @mbggenerated
     */
    public Integer getAgendaRoundNo() {
        return agendaRoundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_score.agenda_round_no
     *
     * @param agendaRoundNo the value for myty_score.agenda_round_no
     *
     * @mbggenerated
     */
    public void setAgendaRoundNo(Integer agendaRoundNo) {
        this.agendaRoundNo = agendaRoundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_score.user_id
     *
     * @return the value of myty_score.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_score.user_id
     *
     * @param userId the value for myty_score.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_score.user_score
     *
     * @return the value of myty_score.user_score
     *
     * @mbggenerated
     */
    public Integer getUserScore() {
        return userScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_score.user_score
     *
     * @param userScore the value for myty_score.user_score
     *
     * @mbggenerated
     */
    public void setUserScore(Integer userScore) {
        this.userScore = userScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_score.score_type
     *
     * @return the value of myty_score.score_type
     *
     * @mbggenerated
     */
    public String getScoreType() {
        return scoreType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_score.score_type
     *
     * @param scoreType the value for myty_score.score_type
     *
     * @mbggenerated
     */
    public void setScoreType(String scoreType) {
        this.scoreType = scoreType;
    }
}