package com.hallth.domain;

public class MytyDengmiTemp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi_temp.dm_mimian
     *
     * @mbggenerated
     */
    private String dmMimian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi_temp.dm_mimu
     *
     * @mbggenerated
     */
    private String dmMimu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi_temp.dm_midi
     *
     * @mbggenerated
     */
    private String dmMidi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi_temp.dm_mimianzhu
     *
     * @mbggenerated
     */
    private String dmMimianzhu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi_temp.dm_midizhu
     *
     * @mbggenerated
     */
    private String dmMidizhu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi_temp.dm_author
     *
     * @mbggenerated
     */
    private String dmAuthor;

    public int getDmTempId() {
        return dmTempId;
    }

    public void setDmTempId(int dmTempId) {
        this.dmTempId = dmTempId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi_temp.dm_author
     *
     * @mbggenerated
     */
    private int dmTempId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myty_dengmi_temp.dm_author
     *
     * @mbggenerated
     */
    private int agendaRoundNo;

    public int getAgendaRoundNo() {
        return agendaRoundNo;
    }

    public void setAgendaRoundNo(int agendaRoundNo) {
        this.agendaRoundNo = agendaRoundNo;
    }

    /**
     * 非数据库字段-用于分页查询,起始行
     * */
    private int startRow;
    /**
     * 非数据库字段-用于分页查询,
     * */
    private int pageSize;
//    /**
//     * 非数据库字段-用于评分
//     * */
//    private int userJudge;
//    /**
//     * 非数据库字段-用于评分
//     * */
//    private int userAnswer;
//
//    public int getUserAnswer() {
//        return userAnswer;
//    }
//
//    public void setUserAnswer(int userAnswer) {
//        this.userAnswer = userAnswer;
//    }
//
//    public int getUserJudge() {
//        return userJudge;
//    }
//
//    public void setUserJudge(int userJudge) {
//        this.userJudge = userJudge;
//    }

    public int getStartRow() {
        return startRow;
    }

    public void setStartRow(int startRow) {
        this.startRow = startRow;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_dengmi_temp.dm_mimian
     *
     * @return the value of myty_dengmi_temp.dm_mimian
     *
     * @mbggenerated
     */
    public String getDmMimian() {
        return dmMimian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_dengmi_temp.dm_mimian
     *
     * @param dmMimian the value for myty_dengmi_temp.dm_mimian
     *
     * @mbggenerated
     */
    public void setDmMimian(String dmMimian) {
        this.dmMimian = dmMimian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_dengmi_temp.dm_mimu
     *
     * @return the value of myty_dengmi_temp.dm_mimu
     *
     * @mbggenerated
     */
    public String getDmMimu() {
        return dmMimu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_dengmi_temp.dm_mimu
     *
     * @param dmMimu the value for myty_dengmi_temp.dm_mimu
     *
     * @mbggenerated
     */
    public void setDmMimu(String dmMimu) {
        this.dmMimu = dmMimu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_dengmi_temp.dm_midi
     *
     * @return the value of myty_dengmi_temp.dm_midi
     *
     * @mbggenerated
     */
    public String getDmMidi() {
        return dmMidi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_dengmi_temp.dm_midi
     *
     * @param dmMidi the value for myty_dengmi_temp.dm_midi
     *
     * @mbggenerated
     */
    public void setDmMidi(String dmMidi) {
        this.dmMidi = dmMidi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_dengmi_temp.dm_mimianzhu
     *
     * @return the value of myty_dengmi_temp.dm_mimianzhu
     *
     * @mbggenerated
     */
    public String getDmMimianzhu() {
        return dmMimianzhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_dengmi_temp.dm_mimianzhu
     *
     * @param dmMimianzhu the value for myty_dengmi_temp.dm_mimianzhu
     *
     * @mbggenerated
     */
    public void setDmMimianzhu(String dmMimianzhu) {
        this.dmMimianzhu = dmMimianzhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_dengmi_temp.dm_midizhu
     *
     * @return the value of myty_dengmi_temp.dm_midizhu
     *
     * @mbggenerated
     */
    public String getDmMidizhu() {
        return dmMidizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_dengmi_temp.dm_midizhu
     *
     * @param dmMidizhu the value for myty_dengmi_temp.dm_midizhu
     *
     * @mbggenerated
     */
    public void setDmMidizhu(String dmMidizhu) {
        this.dmMidizhu = dmMidizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myty_dengmi_temp.dm_author
     *
     * @return the value of myty_dengmi_temp.dm_author
     *
     * @mbggenerated
     */
    public String getDmAuthor() {
        return dmAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myty_dengmi_temp.dm_author
     *
     * @param dmAuthor the value for myty_dengmi_temp.dm_author
     *
     * @mbggenerated
     */
    public void setDmAuthor(String dmAuthor) {
        this.dmAuthor = dmAuthor;
    }
}